# docker-compose.yml
version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # ensure Next.js listens on 0.0.0.0
      - PORT=3000
      # Puppeteer will auto-use its downloaded Chromium; no need to set CHROME_PATH
    restart: unless-stopped
